name: CI

on: [push, pull_request]

jobs:

    buildDebug:
        name: Debug build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            
            -   name: enablee
                run: chmod +x ./gradlew

            -   name: Run debug build
                run: ./gradlew assembleDebug

            -   name: Upload artifact to GitHub
                uses: actions/upload-artifact@v2
                with:
                    name: WhatsappWebTogo-debug.apk
                    path: build/outputs/apk/debug/WhatsappWebTogo-debug.apk
